### ISSUE TITLE
This package has been hijacked

### ISSUE THREAD

**Issue by zeke** [substack/provinces#20]
In the wake of @azer's [mass unpublishing](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.37j7cvuek), someone overwrote `provinces` with a fake package. I'm opening an issue with npm support to get ownership back into the hands of @substack and/or me.

**Comment by substack** [comment]
Is there any way to recover the previous versions?

**Comment by adambrault** [comment]
Well, since this brought me here to confirm that's what was up...

Here's an opportunity to say, "Thank you, @substack for this software and all of your other soft wares." <3

**Comment by zeke** [comment]
> Is there any way to recover the previous versions?

I think not. But we can probably republish a patch-level bump so semver-abiding version ranges will still work.

@substack I opened a support@npmjs.com ticket last night but haven't heard back yet. You may want to open a ticket yourself for a faster turnaround.

![screen shot 2016-03-23 at 8 06 55 pm](https://cloud.githubusercontent.com/assets/2289/14007341/0b0f7ae6-f133-11e5-8663-8ddc3cb89133.png)

**Comment by zeke** [comment]
The npm support team added me and @substack as owners of the package. I just unpublished the bunk `2.0.0` version, and published a patch-level bump from the last "real" version 1.8.0 to 1.8.1. We cannot overwrite existing published versions, so this is the best we can do.

Anyone using a `^1.x.x` or `~1.x.x` semver range should be unaffected. Anyone using a pre-1.0 range is probably out of luck.
