### ISSUE TITLE
Territories in The Netherlands

### ISSUE THREAD

**Issue by jorrit** [substack/provinces#31]
Commit d0785051446124936134ae566a17d84d84879fb4 added territories to The Netherlands. I would like to ask why these territories were added. Curaçao, Sint Maarten and Aruba are countries within the kingdom of The Netherlands. Bonaire, Saba and Sint Eustatius are not provinces but special municipalities of The Netherlands (the country). What is the policy to include them?

**Comment by zeke** [comment]
I became a maintainer of this project long after it was created by @substack, so I can't speak to why certain decisions were made. If you have a good understanding of the geography of the Netherlands (which I suspect you do), feel free to open a pull request that corrects the data.
